# Generated by Django 3.2.6 on 2022-01-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='coordinate1',
            new_name='pitch',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='coordinate2',
            new_name='yaw',
        ),
    ]
