# Generated by Django 3.2.6 on 2022-01-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0002_auto_20220113_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staritem',
            name='emoticon',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='staritem',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
